### PR TITLE
Cannot find module 'rimraf'

### PR DESCRIPTION
**Pull request by amercier**
```
Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### CODE REVIEW

**Comment by amercier** [comment]
This bug was introduced by 5bf7b2a4863a5606eb4393171ddc594bfd6c314e and affects version 2.0.1.
